---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wordpress-mysql-secrets
  namespace: wp
spec:
  encryptedData:
    password: AgBS+htmWx+jGYFuK4dWwhqeaCtVogcmAJKoNedR/xOpuImvgXxd7CMV91vGteNk+521a49MXdOIsIeF7xZE6gFrpcVpsnYTPuTmWDxdVYHTWrouqCMVzetaiH2Q6MPd+IpJzeC08VVC1qVvGGPVRs71DY92n+qIPYScvoybqdgN6L/EhloF88KOjgE6EkrocIQZTlH7r/R/GT1BgcZmLw3B0A9uSn78n1enndvClEEHEFUL92FUaSaFOxu6qtqmv04X97G/9VpvKvslBG+t+AK8NrfaeOpogxp1nJK/73YQ9xZ3HcNHBYKI4J2ERr9ccwfkD7y//JGAoM5tKupqmiPKmNm+URVhdRZaPc7qKcRywXuJh9oR0P5R1Dn+pZpDrmhjwKskLDSRpiCTWW3QXMLkwLqMGJma2qsu/LKuJLSfK7+M2N9lRhgwX4AWf1RDe5qIJq6DCBF15zxKVOyW1Hkum3dnR4mnobzBxyhPsvMV1ZXGvDoRyekw8TL578NHBFc3nqiaJWRbASN49hMlZ0xe/7uJVvNjX3HyikmVkezhGAF7IkdBXsuBOOmDB5hhGeby59FdPhsEBA14TBt5swBizdNIriO+edhGV6LAF3A/F6RpHuIcvyElAXlvI7FTAuGoPC11jwTiTIr1PaoSUktXgEoGIsr3Xu0NyQWBvNnXgjW9TV3T68P3rfScIFiZzNT3qCqC
    root-password: AgCuRngWRKPKcpytd0qlA9sTA42+zQYynMRf4SHpgy99Hl/V65CkD71c1oLs7Tr3BzLnotWWyWI/18MC33Mx7YnFIWKUDTNpwWKO5/ZZDRVtKs+mbB6KPpIbjyVX1zXxjUH+2UlhLNfD7dD/1dNouUIVsrfcbPhsVeKjFPIpALIULyJASMPeSgLXXnSJJZw1V7INrZRhfi8mWrqVwhAuMAlusoH3w2WqjzB++cNVVozfXBKPBV4+NrVeWcIHBs/gtB5WQtxf1ZmgIsLVJ8QCeNcHAysDaVqfs+OvGqtr1+eZ8TknUIJPOCFUkCtcLa05J8l5yBeLxBVZPI2ettKyE/BsaTq3kLAbKOfC3c84BpzTNcevac/MPgMUKfTLW/AYc1nA7lm9n9b+dJUYw+GIVvA0pqhYCYds2ZbERPyRKz2baifbQX+AUdn4SfGeEvOku2EUfEAcsBbFIcGB96rpLgPowaFVvTRA7LwZfhPRRkhuPRLHMVnEVONf0We+V/YVAzUGVDCTur9nsSGUH4pOTZAETTJj/lc1bLcpZuC1UcKmdJnwi6VXbUmmYBnA+iIIZ621xJpHrbpeVjjzmZ4F7EuEgARNgreSw9+1GhQIJZ9g9mBqcnxwZjsBJyl/nU2s0WW9K1rn9rwSX4ZheqTKGjSIZtJtj0MEpJfTfHmp7iT+jpzeU1EmoRr23Pg1BEcG53LbRLEt
  template:
    metadata:
      creationTimestamp: null
      name: wordpress-mysql-secrets
      namespace: wp
